### PR TITLE
feat: Bump DKP-Insights to 0.2.0

### PR DESCRIPTION
**Pull request by kaiwalyajoshi**
Bump Insights to v0.2.0 for DKP 2.3

**What problem does this PR solve?**:

**Which issue(s) does this PR fix?**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**If the PR adds a version bump, does it add a breaking change in License**:

- [ ] No License Change (or NA).

### CODE REVIEW

**Comment by kaiwalyajoshi** [comment]
Will remove `do-not-merge` label once docker images are pushed up.

**Comment by gracedo** [comment]
When docker images are pushed up we can trigger the tests here and get it merged

**Comment by kaiwalyajoshi** [comment]
Docker images pushed, helm releases pushed.

**Review by gracedo — APPROVED** [review]
manually tested upgrade from 0.1.6 to 0.2.0 using the daily cluster

```
Status:
  Conditions:
    Last Transition Time:          2022-07-21T17:29:57Z
    Message:                       Release reconciliation succeeded
    Reason:                        ReconciliationSucceeded
    Status:                        True
    Type:                          Ready
    Last Transition Time:          2022-07-21T17:29:57Z
    Message:                       Helm upgrade succeeded
    Reason:                        UpgradeSucceeded
    Status:                        True
    Type:                          Released
  Helm Chart:                      kommander-flux/kommander-dkp-insights-management
  Last Applied Revision:           v0.2.0
  Last Attempted Revision:         v0.2.0
  Last Attempted Values Checksum:  0b51ede83d6854a870b6c84ae10f996389ed656f
  Last Release Revision:           3
  Observed Generation:             3
Events:
  Type     Reason  Age                From             Message
  ----     ------  ----               ----             -------
  Warning  error   22m                helm-controller  reconciliation failed: Operation cannot be fulfilled on helmreleases.helm.toolkit.fluxcd.io "dkp-insights-management": the object has been modified; please apply your changes to the latest version and try again
  Normal   info    51s (x2 over 12h)  helm-controller  HelmChart 'kommander-flux/kommander-dkp-insights-management' is not ready
  Warning  error   50s (x2 over 51s)  helm-controller  could not find ConfigMap 'kommander/dkp-insights-management-0.2.0-d2iq-defaults'
  Normal   info    49s (x2 over 23m)  helm-controller  Helm upgrade has started
  Normal   info    37s (x2 over 22m)  helm-controller  Helm upgrade succeeded
```

**Review by cbuto — APPROVED** [review]

**Review by takirala — APPROVED** [review]

**Pull request merged**
