### PR TITLE
feat: Release DKP-Insights v0.1.4

### PR DESCRIPTION
**Pull request by kaiwalyajoshi**
- Fixes https://jira.d2iq.com/browse/D2IQ-87165

### CODE REVIEW

**Comment by kaiwalyajoshi** [comment]
Fixes tested on Soak Cluster: https://dkp22.ksphere-soak.d2iq.cloud/dkp/kommander/dashboard/insights

**Review by branden — APPROVED** [review]

**Review by gracedo — APPROVED** [review]

**Comment by kaiwalyajoshi** [comment]
@gracedo just out of curiosity and future reference, why do we need a `needs-backport` label here? Wouldn't this be the first release that's not a `rc` release?

**Comment by gracedo** [comment]
@kaiwalyajoshi we already have a `release-2.2` branch, previously we've been merging `main` into it at rc release time but I think it's cleaner/safer to use mergebot to properly backport changes into the `release-2.2` branch. Merging main was not as simple due to PR's squash-merging into the release branch, causing weird commit diffs and sometimes merge conflicts for some reason

**Comment by gracedo** [comment]
@mesosphere-mergebot backport release-2.2

**Pull request merged**
