### PR TITLE
chore: bump external dns

### PR DESCRIPTION
**Pull request by farhan5900**
https://jira.d2iq.com/browse/D2IQ-85888

This PR is introducing the upstream `bitnami` external-dns, not using the `mesosphere/charts` external-dns.

### CODE REVIEW

**Comment by jimmidyson** [comment]
I've deleted 2.20.5 as @rishabh96b suggested above.

**Review by jimmidyson — CHANGES_REQUESTED** [review]
Looks great, but blocking until we have confirmation that upgrade works. Can you let us know when that is tested please @farhan5900 (sorry if I've missed that you've already done this!)?

**Review by floridoo — APPROVED** [review]

**Comment by farhan5900** [comment]
Thanks, @jimmidyson for the changes, I have tested the upgrade of external-dns manually and it is working fine.

**Review by gracedo — APPROVED** [review]
Lgtm thanks!

Slack thread with @farhan5900 upgrade test results: https://mesosphere.slack.com/archives/C01LNF6KML5/p1646892761526849?thread_ts=1646825384.302359&cid=C01LNF6KML5

**Pull request merged**
