### PR TITLE
feat: Upgrade flux to 0.31.3

### PR DESCRIPTION
**Pull request by mesosphere-teamcity**
- feat: Upgrade flux to 0.31.3

### CODE REVIEW

**Comment by mikolajb** [comment]
I changed the base (to `release-2.2`) and removed `kommander` directory.

**Comment by takirala** [comment]
@mesosphere-mergebot test all

**Review by takirala — APPROVED** [review]

**Comment by takirala** [comment]
@mesosphere-mergebot test all

**Comment by takirala** [comment]
@mesosphere-mergebot test all

**Review by gracedo — APPROVED** [review]

**Review by aweris — APPROVED** [review]

**Pull request merged**
