### PR TITLE
feat: Upgrade flux to 0.28.5

### PR DESCRIPTION
**Pull request by mesosphere-teamcity**
Being tested at [mesophere/kommander#1586](https://github.com/mesosphere/kommander/pull/1586)

### CODE REVIEW

**Comment by gracedo** [comment]
slapping a backport label on here, I think we discussed releasing flux upgrade in a 2.2.1 patch

**Comment by makkes** [comment]
Removing do-not-merge label as the tests over at mesosphere/kommander#1586 passed.

**Review by makkes — APPROVED** [review]

**Review by farhan5900 — APPROVED** [review]

**Comment by takirala** [comment]
Following needs to be merged at the same time.

https://github.com/mesosphere/kommander-cli/pull/475
https://github.com/mesosphere/kommander/pull/1586
https://github.com/mesosphere/kommander-applications/pull/326

**Comment by takirala** [comment]
@mesosphere-mergebot backport release-2.2

**Pull request merged**
