### PR TITLE
[release-2.2][BACKPORT] fix: bump KPS chart based Apps

### PR DESCRIPTION
**Pull request by mesosphere-mergebot**
This is a backport of the following PR:

https://github.com/mesosphere/kommander-applications/pull/375

to fix the grafana view role permission

kommander PR: https://github.com/mesosphere/kommander/pull/1736

https://jira.d2iq.com/browse/D2IQ-88865Before merging, conflicts in the following files need to be resolved: 
services/kube-prometheus-stack/33.1.5/grafana-dashboards/calico.json
services/kube-prometheus-stack/34.9.1/defaults/cm.yaml
services/kube-prometheus-stack/34.9.0/defaults/kustomization.yaml
services/kube-prometheus-stack/34.9.1/grafana-dashboards/flux-cluster-stats.json
services/kube-prometheus-stack/33.1.5/defaults/cm.yaml
services/kube-prometheus-stack/34.9.0/grafana-dashboards/flux-control-plane.json
services/kube-prometheus-stack/34.9.0/grafana-dashboards/flux-cluster-stats.json
services/kube-prometheus-stack/34.9.0/kube-prometheus-stack.yaml
services/kube-prometheus-stack/33.1.5/grafana-dashboards/flux-control-plane.json
services/kube-prometheus-stack/34.9.0/defaults/cm.yaml
services/kube-prometheus-stack/34.9.1/grafana-dashboards/flux-control-plane.json
services/centralized-grafana/34.9.1/defaults/kustomization.yaml
services/centralized-grafana/34.9.0/defaults/kustomization.yaml
services/centralized-grafana/33.1.5/grafana-dashboards/global-overview.json
services/kube-prometheus-stack/34.9.0/kustomization.yaml
services/kommander/0.2.1/defaults/cm.yaml
services/centralized-grafana/33.1.5/grafana-dashboards/kustomization.yaml
services/centralized-grafana/34.9.0/grafana-dashboards/global-overview.json
services/centralized-grafana/34.9.0/grafana-dashboards/kustomization.yaml
services/centralized-grafana/34.9.1/kustomization.yaml
services/centralized-grafana/33.1.5/kustomization.yaml
services/centralized-grafana/33.1.5/centralized-grafana.yaml
services/centralized-grafana/33.1.5/defaults/cm.yaml
services/kube-prometheus-stack/34.9.1/grafana-dashboards/kustomization.yaml
services/kube-prometheus-stack/34.9.0/grafana-dashboards/calico.json
services/kube-prometheus-stack/34.9.0/grafana-dashboards/kustomization.yaml
services/kube-prometheus-stack/34.9.1/kube-prometheus-stack.yaml
services/traefik/10.9.1/defaults/kustomization.yaml
services/kube-prometheus-stack/33.1.5/grafana-dashboards/kustomization.yaml
services/kube-prometheus-stack/34.9.1/defaults/kustomization.yaml
services/kube-prometheus-stack/34.9.0/grafana-dashboards/grafana.json
services/kube-prometheus-stack/33.1.5/kustomization.yaml
services/centralized-grafana/34.9.1/grafana-dashboards/kustomization.yaml
services/centralized-grafana/34.9.1/grafana-dashboards/global-overview.json
services/centralized-grafana/34.9.0/defaults/cm.yaml
services/centralized-grafana/34.9.0/kustomization.yaml
services/centralized-grafana/34.9.1/centralized-grafana.yaml
services/kube-prometheus-stack/33.1.5/kube-prometheus-stack.yaml
services/kube-prometheus-stack/34.9.1/grafana-dashboards/grafana.json
services/kube-prometheus-stack/33.1.5/grafana-dashboards/grafana.json
services/kube-prometheus-stack/33.1.5/grafana-dashboards/flux-cluster-stats.json
services/centralized-grafana/34.9.0/centralized-grafana.yaml
services/kube-prometheus-stack/34.9.1/kustomization.yaml
services/kommander-flux/0.28.5/defaults/kustomization.yaml
services/kube-prometheus-stack/34.9.1/grafana-dashboards/calico.json
services/centralized-grafana/34.9.1/defaults/cm.yaml

### CODE REVIEW

**Review by takirala — DISMISSED** [review]
lets tidy up the commits made by mergebot to make pre-commit happy. lgtm otherwise.

**Review by gracedo — CHANGES_REQUESTED** [review]
this jumps a major version, which we probably don't want to do in a patch release. we need to patch the previous version (33.x) in m/charts and use that one here. it's a bit of a tricky process, I'll see if I find some time to do it today

**Comment by takirala** [comment]
> this jumps a major version, which we probably don't want to do in a patch release.
good call.

**Comment by gracedo** [comment]
@cwyl02 I created a `kube-prometheus-stack-33.1.x` branch in m/charts: https://github.com/mesosphere/charts/tree/release/kube-prometheus-stack-33.1.x if you can open a PR against it with the cherry-picked grafana role fixes, that should do it! (tests don't run properly on backports so they will probably fail)

**Comment by cwyl02** [comment]
closing per discussion in standup

**Pull request closed without merging**
