### PR TITLE
fix: enable reloading on creation of secrets

### PR DESCRIPTION
**Pull request by cbuto**
**What problem does this PR solve?**:
When Loki is deployed, the ceph operator can delete and recreate the dkp-loki secret. We need reloader to reload the loki deployments when the secret is recreated.

**Which issue(s) does this PR fix?**:

https://d2iq.atlassian.net/browse/D2IQ-94260

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

- [ ] If the PR adds a version bump, ensure there is no breaking change in Licensing model (or NA).
- [ ] If a chart is changed or app configuration is significantly changed, the chart version is correctly incremented (so that apps are not automatically upgraded from a previous version of DKP).

### CODE REVIEW

**Review by cwyl02 — APPROVED** [review]

**Review by msdolbey — APPROVED** [review]
👍 
Reload this

**Comment by cbuto** [comment]
backport PR https://github.com/mesosphere/kommander-applications/pull/806

**Comment by cbuto** [comment]
install tests have started failing related to catalog application tests (unrelated to this change). the tests passed initially at https://teamcity.mesosphere.io/buildConfiguration/ClosedSource_Kommander2_KommanderApplications_InstallE2eTests/3694237?buildTab=log&focusLine=3

**Pull request merged**
