### PR TITLE
fix: Add back empty kaptain.yaml file (2.4)

### PR DESCRIPTION
**Pull request by gracedo**
Due to how new kommander-applications is updated during upgrades, the kaptain.yaml helmrepo file continues to exist even after removing it, if it existed in the repo before. To work around this issue for now, adding back an empty kaptain.yaml file works to remove the erroring kaptain helmrepo.

**What problem does this PR solve?**:
backports https://github.com/mesosphere/kommander-applications/pull/1190

**Which issue(s) does this PR fix?**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

- [ ] If the PR adds a version bump, ensure there is no breaking change in Licensing model (or NA).
- [ ] If a chart is changed or app configuration is significantly changed, the chart version is correctly incremented (so that apps are not automatically upgraded from a previous version of DKP).

### CODE REVIEW

**Comment by gracedo** [comment]
@d2iq-mergebot backport release-2.5

**Comment by gracedo** [comment]
@d2iq-mergebot backport release-2.5

**Comment by gracedo** [comment]
@d2iq-mergebot backport release-2.5

**Review by cwyl02 — APPROVED** [review]

**Review by msdolbey — APPROVED** [review]
👍 
The Classic

**Comment by gracedo** [comment]
I don't think the e2e tests are working on release branches.. will ignore these because this fix has gone out in 2.3.3 and verified to work.

**Pull request merged**
