### PR TITLE
chore: bump tfa to 3.2.0

### PR DESCRIPTION
**Pull request by mhrabovcin**
**What problem does this PR solve?**:

**Which issue(s) does this PR fix?**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

- [ ] If the PR adds a version bump, ensure there is no breaking change in Licensing model (or NA).
- [ ] If a chart is changed or app configuration is significantly changed, the chart version is correctly incremented (so that apps are not automatically upgraded from a previous version of DKP).

### CODE REVIEW

**Review by gracedo — APPROVED** [review]

**Comment by gracedo** [comment]
https://github.com/mesosphere/kommander/pull/4984 is ✅

**Comment by mhrabovcin** [comment]
No backport of this PR to not affect 2.12 rls.

**Comment by mhrabovcin** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|release-2.12|[](https://github.com/mesosphere/kommander-applications/pull/2589)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by mhrabovcin** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|release-2.12|[](https://github.com/mesosphere/kommander-applications/pull/2589)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
