### PR TITLE
feat: Bump fluent-bit to 0.22.0

### PR DESCRIPTION
**Pull request by gracedo**
This upgrades fluent-bit to 0.22.0 to use the latest upstream chart fluent-bit 0.22.0.

### CODE REVIEW

**Review by cbuto — APPROVED** [review]

**Comment by gracedo** [comment]
@d2iq-mergebot test all

**Comment by gracedo** [comment]
@d2iq-mergebot test all

**Comment by gracedo** [comment]
superseded by https://github.com/mesosphere/kommander-applications/pull/957

**Pull request closed without merging**
