### PR TITLE
chore: bump kube-prometheus-stack chart to 18.1.2

### PR DESCRIPTION
**Pull request by mhrabovcin**
https://github.com/mesosphere/charts/pull/1265
Adds the concurrency policy `Replace` configuration to the set home dashboards `CronJob` to avoid potentially creating an unbound number of pods if a pod is failing to start.

JIRA: https://jira.d2iq.com/browse/COPS-7105

### CODE REVIEW

**Review by takirala — APPROVED** [review]
https://github.com/mesosphere/kommander/blob/9f99c2b771bda00b991f1078769644e7554f7424/chart/kommander/templates/controllermanager/deployment_controllermanager.yaml#L46 needs to be updated too

**Review by gracedo — APPROVED** [review]

**Comment by mhrabovcin** [comment]
@takirala I've created https://github.com/mesosphere/kommander/pull/1332 but I am not sure how to order merging of these 2 PRs or how to "sync" them.

**Comment by gracedo** [comment]
@mhrabovcin to test the bump on kommander, you can point the kommander-applications sha to the one on your branch here here, wait for tests to pass, then merge this PR and point the sha back to main https://github.com/mesosphere/kommander/blob/fbce3ed24f48b737e789281e8f11a4f71ce6911a/Makefile#L60

**Comment by mhrabovcin** [comment]
@takirala @gracedo is there anything else required for this PR?

**Comment by gracedo** [comment]
@mhrabovcin Nope! We're all just kinda stuck in a holding pattern right now because airgapped tests are broken on `main` so we haven't been merging anything. We're holding on merging k-apps PRs since `kommander` will break once these k-apps changes go out into `main` without the corresponding `kommander` PR getting merged (except these PRs aren't green yet, due to aforementioned failing airgapped tests). Hopefully we'll resolve the test today, and I can take over your PRs and get them merged in!

**Comment by gracedo** [comment]
@mesosphere-mergebot backport release-2.1

**Pull request merged**
