### PR TITLE
feat: Enable "lazy" connector initialization in dex

### PR DESCRIPTION
**Pull request by dlipovetsky**
**What problem does this PR solve?**:
Allows dex server to start even if one or more connectors is misconfigured.

This change does not affect any other dex functionality, and we want to automatically apply this fix, so I'm not bumping the chart version.

**Which issue(s) does this PR fix?**:

https://d2iq.atlassian.net/browse/D2IQ-95346

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
dex: Allow server to start even if one or more connector is misconfigured.
```

**Checklist**

- [x] If the PR adds a version bump, ensure there is no breaking change in Licensing model (or NA).
- [x] If a chart is changed or app configuration is significantly changed, the chart version is correctly incremented (so that apps are not automatically upgraded from a previous version of DKP).

### CODE REVIEW

**Review by msdolbey — APPROVED** [review]
👍 
I like it. 

I know I wasn't asked for a review, but YOU'RE STILL GETTING IT.

nice

**Comment by dlipovetsky** [comment]
Updated license metadata and force-pushed.

**Comment by gracedo** [comment]
@mesosphere-mergebot test all

**Review by palexster — APPROVED** [review]

**Comment by gracedo** [comment]
opened/closed hoping it would trigger the `Validate PR title` and `pre-commit` actions.. but no luck 🥲 we can admin merge it. PR title looks good, and we have the TC job `kommander-applications/pre-commit` passing.

**Comment by palexster** [comment]
@mesosphere-mergebot backport  2.4

**Pull request merged**
