### PR TITLE
feat: recategorize istio, kiali, jaeger as platform app, add supported and certified bages

### PR DESCRIPTION
**Pull request by mstruebing**
**What problem does this PR solve?**:

This PR categorizes istio as an platform application.

**Which issue(s) does this PR fix?**:

https://d2iq.atlassian.net/browse/D2IQ-95625

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
* Istio, kiali and jaeger are now a platform applications
```

**Checklist**

- [ ] If the PR adds a version bump, ensure there is no breaking change in Licensing model (or NA).
- [ ] If a chart is changed or app configuration is significantly changed, the chart version is correctly incremented (so that apps are not automatically upgraded from a previous version of DKP).

### CODE REVIEW

**Review by clintonmedbery — CHANGES_REQUESTED** [review]
According to the epic reqs we need to label Kiali and Jaegar as Platform Applications as well. I am requesting those changes to keep that from getting merged prematurely. If you rather do this in another PR LMK and I will approve.

**Comment by mstruebing** [comment]
Please take another look @clintonmedbery

**Review by clintonmedbery — APPROVED** [review]
Nice!

**Comment by mstruebing** [comment]
Closed in favour of #971

**Pull request closed without merging**
