### PR TITLE
fix: bump KPS chart based Apps

### PR DESCRIPTION
**Pull request by cwyl02**
to fix the grafana view role permission

kommander PR: https://github.com/mesosphere/kommander/pull/1736

https://jira.d2iq.com/browse/D2IQ-88865

### CODE REVIEW

**Review by gracedo — APPROVED** [review]

**Review by cbuto — APPROVED** [review]

**Comment by cwyl02** [comment]
tests are all green in https://github.com/mesosphere/kommander/pull/1736

**Review by branden — APPROVED** [review]

**Comment by gracedo** [comment]
We should backport this, but it will involve backporting KPS chart since we've upgraded it since 2.2. I can take a look at this later but let's keep it on our radar for 2.2.1 patch cc @takirala

**Comment by takirala** [comment]
ack.

**Comment by cwyl02** [comment]
@mesosphere-mergebot backport release-2.2

**Pull request merged**
