### PR TITLE
build: add lint:precommit target to mage

### PR DESCRIPTION
**Pull request by aweris**
**What problem does this PR solve?**:

Introduces mage + dagger setup with new precommit check. 

- An example  [workflow run](https://github.com/mesosphere/kommander-applications/actions/runs/3532343165/jobs/5926576657) can be found in the link

Available Targets :

```
› ./mage                     
Targets:
  ...
  lint:precommit    runs all the precommit checks.
```

Local execution: 
```
 › ./mage lint:precommit      
#1 local:///home/aweris/development/workspaces/github.com/mesosphere/kommander-applications
#1 DONE 0.0s

#1 local:///home/aweris/development/workspaces/github.com/mesosphere/kommander-applications
#1 transferring /home/aweris/development/workspaces/github.com/mesosphere/kommander-applications: 390.64kB 0.0s done
#1 DONE 0.1s

#2 copy / /
#2 DONE 0.1s

#3 resolve image config for docker.io/library/python:3.12.0a1-bullseye
#3 DONE 0.5s

#4 mkfile /Dockerfile
#4 DONE 0.0s

#5 mkfile /main.go
#5 CACHED

#6 [internal] load metadata for docker.io/library/golang:1.18.2-alpine
#6 DONE 0.3s

#7 mkdir /meta
#7 CACHED

#8 [build 1/6] FROM docker.io/library/golang:1.18.2-alpine@sha256:4795c5d21f01e0777707ada02408debe77fe31848be97cf9fa8a1462da78d949
#8 resolve docker.io/library/golang:1.18.2-alpine@sha256:4795c5d21f01e0777707ada02408debe77fe31848be97cf9fa8a1462da78d949 done
#8 DONE 0.0s

#9 [build 4/6] RUN go mod init go.dagger.io/dagger/shim/cmd
#9 CACHED

#10 [build 6/6] RUN CGO_ENABLED=0 go build -o /_shim -ldflags '-s -d -w' .
#10 CACHED

#11 [build 2/6] WORKDIR /src
#11 CACHED

#12 [build 3/6] RUN apk add --no-cache file git
#12 CACHED

#13 [build 5/6] COPY . .
#13 CACHED

#14 [stage-1 1/1] COPY --from=build /_shim /_shim
#14 CACHED

#15 docker-image://docker.io/library/python:3.12.0a1-bullseye
#15 resolve docker.io/library/python:3.12.0a1-bullseye
#15 resolve docker.io/library/python:3.12.0a1-bullseye 0.2s done
#15 DONE 0.2s

#16 curl --location --fail --silent --show-error --output /usr/local/bin/pre-commit-2.20.0.pyz https://github.com/pre-commit/pre-commit/releases/download/v2.20.0/pre-commit-2.20.0.pyz
#16 CACHED

#17 python /usr/local/bin/pre-commit-2.20.0.pyz run --all-files --show-diff-on-failure
#17 0.645 [INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
#17 1.495 [INFO] Initializing environment for https://github.com/jumanjihouse/pre-commit-hooks.
#17 2.490 [INFO] Initializing environment for https://github.com/shellcheck-py/shellcheck-py.
#17 4.008 [INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
#17 4.008 [INFO] Once installed this environment will be reused.
#17 4.008 [INFO] This may take a few minutes...
#17 8.844 [INFO] Installing environment for https://github.com/shellcheck-py/shellcheck-py.
#17 8.844 [INFO] Once installed this environment will be reused.
#17 8.844 [INFO] This may take a few minutes...
#17 13.03 Check service metadata exists............................................Passed
#17 13.07 Check default apps versions..............................................Passed
#17 13.08 Trim Trailing Whitespace.................................................Passed
#17 13.17 Mixed line ending........................................................Passed
#17 13.25 Don't commit to branch...................................................Passed
#17 13.29 Check for added large files..............................................Passed
#17 13.41 Check for case conflicts.................................................Passed
#17 13.53 Check for merge conflicts................................................Passed
#17 13.64 Check that executables have shebangs.....................................Passed
#17 13.67 Check for broken symlinks............................(no files to check)Skipped
#17 13.67 Fix End of Files.........................................................Passed
#17 13.81 Non-executable shell script filename ends in .sh.....(no files to check)Skipped
#17 13.81 shellcheck...............................................................Passed
#17 DONE 14.0s
```

Depends on #832

### CODE REVIEW

**Review by Azhovan — APPROVED** [review]

**Comment by Azhovan** [comment]
@aweris 
I tried to add some extra white space to a file and run the pre-commit check, here is the output 
```
Error: input:1: container.from.exec.withMountedCache.withEnvVariable.withMountedDirectory.withWorkdir.exec.stdout.contents process "/_shim python /usr/local/bin/pre-commit-2.20.0.pyz run --all-files --show-diff-on-failure" did not complete successfully: exit code: 1

Please visit https://dagger.io/help#go for troubleshooting guidance.
exit status 1
```

**Comment by aweris** [comment]
@Azhovan Can you run same command with `./mage -v lint:precommit` ?

**Comment by aweris** [comment]
I found the bug, it's in the `daggers` lib not here. Fixing at the moment

**Comment by aweris** [comment]
I'll make some changes in `daggers` unfortunately it's a known issue by dagger https://github.com/dagger/dagger/issues/3192

**Comment by aweris** [comment]
Updated `mesosphere/daggers` version for workaround the issue

**Comment by Azhovan** [comment]
@aweris 
now I see the output, much better 
```
#17 python /usr/local/bin/pre-commit-2.20.0.pyz run --all-files --show-diff-on-failure
#17 0.748 Check service metadata exists............................................Passed
#17 0.787 Check default apps versions..............................................Passed
#17 0.799 Trim Trailing Whitespace.................................................Passed
#17 0.895 Mixed line ending........................................................Passed
#17 0.959 Don't commit to branch...................................................Passed
#17 0.988 Check for added large files..............................................Passed
#17 1.064 Check for case conflicts.................................................Passed
#17 1.133 Check for merge conflicts................................................Passed
#17 1.202 Check that executables have shebangs.....................................Passed
#17 1.230 Check for broken symlinks............................(no files to check)Skipped
#17 1.231 Fix End of Files.........................................................Failed
#17 1.347 - hook id: end-of-file-fixer
#17 1.347 - exit code: 1
#17 1.347 - files were modified by this hook
#17 1.347 
#17 1.347 Fixing .github/workflows/automerge.yaml
#17 1.347 
#17 1.348 Non-executable shell script filename ends in .sh.....(no files to check)Skipped
#17 1.348 shellcheck...............................................................Passed
#17 ERROR: process "/_shim python /usr/local/bin/pre-commit-2.20.0.pyz run --all-files --show-diff-on-failure" did not complete successfully: exit code: 1
------
 > python /usr/local/bin/pre-commit-2.20.0.pyz run --all-files --show-diff-on-failure:
#17 0.799 Trim Trailing Whitespace.................................................Passed
Failed
#17 1.347 - hook id: end-of-file-fixer
#17 1.347 - exit code: 1
#17 1.347 - files were modified by this hook
#17 1.347 
#17 1.347 Fixing .github/workflows/automerge.yaml
#17 1.347 
#17 1.348 Non-executable shell script filename ends in .sh.....(no files to check)Skipped
#17 1.348 shellcheck...............................................................Passed
------
Error: input:1: container.from.exec.withMountedCache.withEnvVariable.withMountedDirectory.withWorkdir.exec.stdout.contents process "/_shim python /usr/local/bin/pre-commit-2.20.0.pyz run --all-files --show-diff-on-failure" did not complete successfully: exit code: 1

Please visit https://dagger.io/help#go for troubleshooting guidance.
exit status 1
```

**Review by mikolajb — APPROVED** [review]
Should `mage` have `precommit:install` target?

**Review by cbuto — APPROVED** [review]

**Comment by aweris** [comment]
> Should mage have precommit:install target?

**Pull request merged**
