### PR TITLE
feat(kommander): Remove SSO from default mgmt apps

### PR DESCRIPTION
**Pull request by gracedo**
**What problem does this PR solve?**:
we decided to move SSO apps into kcore to install

**Which issue(s) does this PR fix?**:

https://jira.nutanix.com/browse/NCN-101330

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

- [ ] If the PR adds a version bump, ensure there is no breaking change in Licensing model (or NA).
- [ ] If a chart is changed or app configuration is significantly changed, the chart version is correctly incremented (so that apps are not automatically upgraded from a previous version of DKP).

### CODE REVIEW

**Comment by dkoshkin** [comment]
Konvoy is getting closer to integrating with this and waiting on this condition, anything blocking this PR from being marked ready?

**Comment by gracedo** [comment]
> Konvoy is getting closer to integrating with this and waiting on this condition, anything blocking this PR from being marked ready?

@dkoshkin still testing 🥲 but the condition won't change, so this shouldn't block konvoy. The condition will just wait for more apps when this is merged

**Review by mikolajb — APPROVED** [review]

**Comment by mhrabovcin** [comment]
@gracedo why do we need those new overrides definitions?

**Comment by gracedo** [comment]
> @gracedo why do we need those new overrides definitions?

@mhrabovcin this is more to maintain backwards-compatibility with how kcli install is currently used. If a user configures an app in the installation config yaml, we should process it and apply it to these core apps (deployed by kommander-operator) automatically at install instead of installing the core apps with default config and then in later kcli step, applying the override configs (resulting in reinstall). In many of our docs we ask users to provide config overrides in installation yaml file (e.g. acme docs) and I am worried that if we do not apply overrides at install, it may cause the deployment to fail.

For nutanix clusters (using prompt-based cli) nothing changes since we do not allow app configuration. But just in case if we ever needed a workaround to apply overrides at install, we can provide this (unofficially) by asking them to manually create these override cms before we hit the deployment step.

Longer-term, in a later release we will design a solution to allow passing user configuration for apps into the operator

**Comment by mhrabovcin** [comment]
Thanks @gracedo

**Pull request merged**
