### PR TITLE
fix: Bump velero to 3.1.5 (CVE)

### PR DESCRIPTION
**Pull request by gracedo**
https://jira.d2iq.com/browse/COPS-7134

Velero deploys Minio as a subchart, and that minio was running an old version that was affected by CVE https://cve.mitre.org/cgi-bin/cvename.cgi?name=2021-21287. https://github.com/mesosphere/charts/pull/1268 bumps that minio image to one that includes the CVE fix.

### CODE REVIEW

**Review by takirala — APPROVED** [review]

**Comment by gracedo** [comment]
@mesosphere-mergebot backport release/2

**Comment by gracedo** [comment]
@mesosphere-mergebot backport release/2.1

**Comment by gracedo** [comment]
🤦🏻‍♀️  been working in kba too much recently lol

@mesosphere-mergebot backport release-2.1

**Comment by gracedo** [comment]
@mesosphere-mergebot backport release-2.1

**Review by makkes — APPROVED** [review]

**Pull request merged**
