### PR TITLE
chore: bump dex

### PR DESCRIPTION
**Pull request by vespian**
https://jira.d2iq.com/browse/D2IQ-84494

K20 repo bump: https://github.com/mesosphere/kommander/pull/1748

### CODE REVIEW

**Review by mhrabovcin — APPROVED** [review]

**Review by gracedo — APPROVED** [review]

**Comment by gracedo** [comment]
should we test this on kommander repo first to make sure CI passes before merging this?

**Comment by vespian** [comment]
tested in https://github.com/mesosphere/kommander/pull/1748

**Comment by vespian** [comment]
@gracedo `centralised-monitoring` is failing consistently (e.g. [here](https://teamcity.mesosphere.io/buildConfiguration/ClosedSource_Kommander2_KuttlTests/3440424?buildTab=log&focusLine=3068&expandAll=true)):
```
14:12:35            rules:
14:12:35           - nonResourceURLs:
14:12:35             - /dkp/kommander/monitoring/grafana
14:12:35             - /dkp/kommander/monitoring/grafana/*
14:12:35          -  - /dkp/kommander/monitoring/grafana/api/datasources/proxy/*
14:12:35          +  verbs:
14:12:35          +  - get
14:12:35          +  - head
14:12:35           - nonResourceURLs:
14:12:35          -  - /dkp/kommander/monitoring/grafana/api/datasources/proxy/*
14:12:35          +  - /dkp/kommander/monitoring/grafana/api/datasources/proxy/1/api/v1/series
14:12:35             - /dkp/kommander/monitoring/grafana/api/ds/query
14:12:35             - /dkp/kommander/monitoring/grafana/api/frontend-metrics
```
This seems to me to be unrelated - do you have some context maybe? If not, then I will take a closer look.

**Comment by takirala** [comment]
i pulled in latest changes from `main` into this PR and retriggered kommander CI. I think the CI will pass now :crossed_fingers:

**Comment by vespian** [comment]
>i pulled in latest changes from main into this PR and retriggered kommander CI. I think the CI will pass now 

It helped, thank you @takirala !

**Comment by vespian** [comment]
CI went green, can we merge it now please :pray:  ?

**Comment by gracedo** [comment]
@vespian yes, because you asked so nicely! 😄

**Pull request merged**
