### PR TITLE
chore: remove Kaptain internal HelmRepository (2.3)

### PR DESCRIPTION
**Pull request by gracedo**
# Backport

This will backport the following commits from `main` to `release-2.3`:
 - [chore: Remove Kaptain internal HelmRepository (#845)](https://github.com/mesosphere/kommander-applications/pull/845)

Seeing the same issues in kommander controller failing to reconcile the workspace kustomization due to the cluster kustomization never getting ready because of the failing HelmRepository

```
k get helmrepository -n kommander-flux kaptain-helm-mirror -oyaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  creationTimestamp: "2023-04-19T20:23:11Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: cluster
    kustomize.toolkit.fluxcd.io/namespace: kommander
  name: kaptain-helm-mirror
  namespace: kommander-flux
  resourceVersion: "173170"
  uid: d3f1e588-32c3-4095-827b-e3da375abefc
spec:
  interval: 10m
  timeout: 1m
  url: http://kaptain-helm-mirror.kommander.svc
status:
  conditions:
  - lastTransitionTime: "2023-04-19T20:23:12Z"
    message: no artifact for resource in storage
    observedGeneration: 1
    reason: NoArtifact
    status: "True"
    type: Reconciling
  - lastTransitionTime: "2023-04-19T20:23:12Z"
    message: 'failed to fetch Helm repository index: failed to cache index to temporary
      file: Get "http://kaptain-helm-mirror.kommander.svc/index.yaml": dial tcp: lookup
      kaptain-helm-mirror.kommander.svc on 10.96.0.10:53: no such host'
    observedGeneration: 1
    reason: Failed
    status: "False"
    type: Ready
  - lastTransitionTime: "2023-04-19T20:23:12Z"
    message: 'failed to fetch Helm repository index: failed to cache index to temporary
      file: Get "http://kaptain-helm-mirror.kommander.svc/index.yaml": dial tcp: lookup
      kaptain-helm-mirror.kommander.svc on 10.96.0.10:53: no such host'
    observedGeneration: 1
    reason: Failed
    status: "True"
    type: FetchFailed
  observedGeneration: -1
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

### CODE REVIEW

**Review by jonathanbeber — APPROVED** [review]

**Comment by gracedo** [comment]
@alembiewski Can you take a look and make sure we can remove the kaptain helmrepo from 2.3.3? Was it moved out to a separate repo in this version?

**Comment by gracedo** [comment]
@d2iq-dispatch test all

**Review by takirala — APPROVED** [review]

**Review by msdolbey — APPROVED** [review]
👍 
Cut It Out

**Comment by gracedo** [comment]
e2e tests here won't work on 2.3 release branch. I am just waiting for CI on kommander https://github.com/mesosphere/kommander/pull/3335 to make sure this doesn't break CI there for some reason

**Pull request merged**
