### PR TITLE
feat: Change Insights app names from dkp to nkp

### PR DESCRIPTION
**Pull request by lukeogg**
**What problem does this PR solve?**:

Insights Rename

**Which issue(s) does this PR fix?**:

https://jira.nutanix.com/browse/NCN-100983

**Special notes for your reviewer**:

This likely requires the Insights changes to be merged and released first.

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

- [ ] If the PR adds a version bump, ensure there is no breaking change in Licensing model (or NA).
- [ ] If a chart is changed or app configuration is significantly changed, the chart version is correctly incremented (so that apps are not automatically upgraded from a previous version of DKP).

### CODE REVIEW

**Comment by kaiwalyajoshi** [comment]
@lukeogg 

Let's keep this PR open with a `do-not-merge`, and try to upstream all of your `DKP` -> `NKP` fixes to `dkp-insights` first and trigger the usual release flow.

That will create a new PR here which we can then amend with updates like `mesosphere-repos.yaml` which are found in this PR.

Hopefully, this way we'll have a few atomic commits we can revert if things go really bad.

**Comment by gracedo** [comment]
we would also need to update kcli install config https://github.com/mesosphere/kommander-cli/blob/main/pkg/installer/config/k2dot12config.go to use the new app name.. and possibly elsewhere? and not sure how upgrades look, do we need to add an upgrader to do the migration?

**Comment by kaiwalyajoshi** [comment]
No known customers who've bought a non-trial license, so we're doing all these breaking changes now before customers come with NKP 2.12.

**Comment by kaiwalyajoshi** [comment]
#2478 has been released with all the NKP renames as `v1.2.0-beta.1`, will rebase this atop of #2478.

**Comment by kaiwalyajoshi** [comment]
Sorry, #2478 is an invalid PR, the patches weren't backported to the `release-v1.2` branch on `dkp-insights` repo.

**Comment by kaiwalyajoshi** [comment]
I've merged many of these changes into #2480 which is based on a newer v1.2.0-beta.0 version.

**Comment by gracedo** [comment]
closing, done in https://github.com/mesosphere/kommander-applications/pull/2480

**Pull request closed without merging**
