### PR TITLE
fix: increase requests to flux avoid misfunctioning

### PR DESCRIPTION
**Pull request by palexster**
**What problem does this PR solve?**:

This PR increases CPU and Memory requests for `kustomize` and `source` controllers to avoid observed throttling and protect those controllers from OOM kills.

**Which issue(s) does this PR fix?**:

https://d2iq.atlassian.net/browse/D2IQ-93893

### CODE REVIEW

**Review by Azhovan — APPROVED** [review]

**Review by mikolajb — APPROVED** [review]

**Review by cbuto — CHANGES_REQUESTED** [review]
we'll need to add these patches here: https://github.com/mesosphere/kommander-applications/blob/main/hack/flux/flux-update-kustomization.yaml#L5-L29 so they are retained after a Flux upgrade

**Review by takirala — CHANGES_REQUESTED** [review]
These changes needs to be written in the patch file we apply after auto-updating flux. Otherwise, these changes will get overwritten in a future auto flux update.
https://github.com/mesosphere/kommander-applications/blob/main/hack/flux/flux-update-kustomization.yaml

**Comment by palexster** [comment]
@takirala @cbuto got it, thanks a lot!

**Review by takirala — COMMENTED** [review]
What i wanted to say was - you need to add changes in the patch file && the actual manifests of source controller and kustomize controller.

In the future automated flux upgrade PRs, the script ll apply the patch to the manifests but we need to do it manually just this once in the current PR. Sorry for the confusion :D

**Comment by gracedo** [comment]
@takirala @cbuto @palexster I pushed the changes to the manifests, double check?

**Comment by palexster** [comment]
Thanks, @gracedo ! :pray:

**Pull request merged**
