### PR TITLE
chore: Update Charts of KPS to 18.1.1 & Grafana to 6.16.14

### PR DESCRIPTION
**Pull request by rishabh96b**
This PR updates
- `kube-prometheus-stack` chart to `18.1.1`
- `Grafana` chart to `6.16.14`
Above chart uses updated images of grafana(`v8.2.1`) which is the last release of `8.x` major version and accompanies the critical CVE fixes. 

Resolves: https://jira.d2iq.com/browse/D2IQ-81262

### CODE REVIEW

**Review by vespian — APPROVED** [review]

**Review by tillt — APPROVED** [review]

**Comment by rishabh96b** [comment]
Created https://jira.d2iq.com/browse/D2IQ-81558 for inconsistencies in `pluginVersion` across different dashboards.

**Comment by gracedo** [comment]
Let's wait to merge this until the kommander PR passes CI https://github.com/mesosphere/kommander/pull/1174 I've updated it to point to this branch. I was seeing that the airgapped tests were failing to deploy kps, so that needs to be looked into before we merge this bump.

**Review by gracedo — APPROVED** [review]
Unblocking, https://github.com/mesosphere/kommander/pull/1174 is looking green (1.22 airgapped test not required/supported yet). Just need to resolve merge conflicts then we can merge

**Comment by rishabh96b** [comment]
@mesosphere-mergebot backport

**Comment by rishabh96b** [comment]
@gracedo is it possible to create a backport PR for this using mergebot? Doesn't seem to work though.

**Comment by gracedo** [comment]
@mesosphere-mergebot backport release-2.1

**Comment by gracedo** [comment]
@rishabh96b you need to specify the backport branch at the end of that command!

**Comment by gracedo** [comment]
@mesosphere-mergebot backport release-2.1

**Comment by gracedo** [comment]
@mesosphere-mergebot backport release-2.1

**Comment by gracedo** [comment]
@mesosphere-mergebot backport release-2.1

**Comment by gracedo** [comment]
ok that's my last attempt, not sure why mergebot isn't doing its thing here .. we'll have to manually opeb up a pr against `release-2.1` and cherry-pick the commits over. this would go into a patch release though, but kps includes a major version change, which makes me think there is a breaking change in there. We probably don't want to be bumping any major versions between patches? If there are just image bumps, can we just bump the images?

**Comment by rishabh96b** [comment]
I think the branch was deleted and that's why it is not triggering the backport PR. Let me try once again.

**Comment by rishabh96b** [comment]
@mesosphere-mergebot backport release-2.1

**Comment by rishabh96b** [comment]
@mesosphere-mergebot backport release-2.1

**Comment by rishabh96b** [comment]
@mesosphere-mergebot backport release-2.1

**Comment by gracedo** [comment]
@rishabh96b I don't think backport is working for this branch anymore, you'll have to open a new branch and cherry-pick the changes

**Pull request merged**
